# -*- coding: utf-8 -*-
INSERT INTO lrlz_car_crawl(type_id,
                           brand_name,
                           series_name,
                           settings,
                           car_name,
                           car_level_str,
                           energy_type_str,
                           market_time,
                           max_power,
                           max_torque,
                           engine,
                           gearbox,
                           car_size,
                           car_struct,
                           max_speed,
                           official_speedup,
                           actual_speedup,
                           actual_brake,
                           gerenal_fueluse,
                           actual_fueluse,
                           quality_guarantee,
                           length,
                           width,
                           height,
                           shaft_distance,
                           front_wheels_gap,
                           back_wheels_gap,min_ground,body_struct,doors,seats,fuel_vol,cargo_vol,total_weight,engine_type,cc,air_intake,cylinder_arrange,cylinders,valves,compress_rate,valve_machanism,cylinder_radius,stroke,engine_hp,engine_power,engine_rpm,engine_torque,torque_rpm,engine_energy,roz,oil_drive,cylinder_cover,cylinder_body,environmental_standard,motor_power,motor_front_power,motor_front_torque,motor_back_power,motor_back_torque,mileage,bat_cap,gears_num,gears_type,gearbox_name,drive_method,susp_front_type,susp_back_type,assist_type,structure,front_brake,back_brake,park_brake,front_wheel_size,back_wheel_size,backup_wheel,seat_srs,side_airbag,head_srs,knee_srs,tire_pres_monitor,zero_tire_pres,unbelt_notice,isofix,anti_lock,bas,tcs,stable_control,bsa,ldw,abs,nvs,radar,reverse_video,panorama,cruise_ctrl,self_adpt_cruise,auto_park_in,engine_start_stop,hac,auto_park,hdc,variable_susp,air_susp,vgrs,front_diff_lock,central_diff_lock,back_diff_lock,ads,e_sunroof,pano_sunroof,alloy_wheel,e_suction_door,slide_door,e_cargo,react_cargo,roof_rack,engine_e_guard,e_ctrl_lock,remote_key,keyless_start,keyless_enter,remote_start,leather_steering,steer_adjt,steer_e_adjt,functional_steer,steer_shift,steer_heat,steer_mem,computer_scr,hud,car_dvr,anc,wireless_charge,seat_mat,sport_seat,height_adjt,lumbar_support,shoulder_support,seat_e_adjt,snd_backrest_adjt,snd_seat_mv,back_seat_adjt,e_seat_mem,seat_heat,seat_vent,seat_masg,third_row_seat,back_seat_down,handrail,back_cup_hold,gps,colorful_scr,colorful_scr_size,lcd_sep,blueteeth,mobile_map,network,television,back_lcd,back_power_supply,cddvd,speaker_brand,speaker_num,low_beam,high_beam,led_beam,adaptive_beam,head_light,turn_light,turn_head_light,front_fog_lamp,light_height_adjt,light_clean_dev,mood_light,power_window,e_lift_window,anti_pinch_hand,insulating_glass,e_adjt_rearview,heat_rearview,dimming_mirror,stream_media_rearview,power_mirror,mirror_mem,abat_vent,side_abat_vent,side_priv_glass,sun_shield,back_wiper,react_wiper,air_type,back_air,back_outlet,temper_zone_ctrl,air_adjt,air_cleaner,car_fridge) VALUE ("35279,长安汽车,长安CS55,https://car.autohome.com.cn/config/spec/35279.html,长安CS55 2018款 1.5T 自动蓝动型,紧凑型SUV,油电混合,2018.09,-,-,1.5T 156马力 L4,6挡手自一体,4500*1855*1690,5门5座SUV,-,-,11.25,40.54,-,7,三年或10万公里,4500,1855,1690,2650,-,-,-,SUV,5,5,58,-,1530,50,1499,涡轮增压,L,4,4,-,DOHC,-,-,156,115,5500,225,2000-4000,油电混合,92号,多点电喷,铝合金,铝合金,V,11.5,-,-,-,-,-,-,6,手自一体变速箱(AT),6挡手自一体,前置前驱,麦弗逊式独立悬架,多连杆独立悬架,电动助力,承载式,通风盘,盘,电子驻车,225/55 R18,225/55 R18,非全尺寸,主●/副●,前●/后-,前●/后●,-,●,-,●,●,●,●,●,●,-,-,-,-,前-/后●,●,-,●,-,-,-,●,-,●,-,-,-,-,-,-,-,●,-,●,-,-,-,-,●,●,●,●,●,●,-,●,上下+前后调节,-,●,-,-,-,●,-,-,-,-,仿皮,-,●,-,-,-,●,-,-,-,-,-,-,-,比例放倒,前●/后●,●,●,●,8英寸,-,●,●,-,-,-,-,-,-,6-7喇叭,LED,LED,●,-,●,-,-,-,●,-,-,前●/后●,主驾驶位,●,-,●,●,-,-,●,-,-,-,-,●,●,●,手动●,-,●,-,-,-,-")